#!/bin/bash
# This script was taken from https://github.com/ramr/nodejs-custom-version-openshift
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.
